home:
    path: /
    controller: App\Controller\IndexController::index
user_registration:
    path: /register
    controller: App\Controller\RegistrationController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout